version: '3.8'

services:
  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-lamsa123}
    volumes:
      - redis_data:/data
    networks:
      - lamsa_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Lamsa API (Minimal)
  api:
    build:
      context: ./lamsa-api
      dockerfile: Dockerfile.minimal
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=15m
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-lamsa123}
      - APP_NAME=${APP_NAME:-Lamsa}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-ar}
      - CURRENCY=${CURRENCY:-JOD}
      - TIMEZONE=${TIMEZONE:-Asia/Amman}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - lamsa_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
    driver: local

networks:
  lamsa_network:
    driver: bridge
