version: '3.8'

services:
  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass lamsa123
    volumes:
      - redis_dev_data:/data
    networks:
      - lamsa_dev

  # Lamsa API - Development
  api:
    build:
      context: ./lamsa-api
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./lamsa-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=lamsa123
      - ENABLE_SWAGGER=true
      - ENABLE_MORGAN_LOGGING=true
      - ENABLE_DETAILED_LOGGING=true
    depends_on:
      - redis
    networks:
      - lamsa_dev

  # Lamsa Web - Development
  web:
    build:
      context: ./lamsa-web
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./lamsa-web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - api
    networks:
      - lamsa_dev

volumes:
  redis_dev_data:
    driver: local

networks:
  lamsa_dev:
    driver: bridge