name: Claude Code

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: anthropics/claude-code-action@v1
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}